name: Build Library

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Library

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Build Library
        run: npm run build:lib
      # - name: Create base repo
      #   if: success()
      #   working-directory: dist/extensions
      #   run: git init && git checkout -b dist
      # - name: Set config
      #   working-directory: dist/extensions
      #   run: git config user.email "${{github.actor}}@github.com" && git config user.name "${{github.repository_owner}}"
      # - name: Add remote
      #   working-directory: dist/extensions
      #   run: git remote add origin https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git
      # - name: Add files
      #   working-directory: dist/extensions
      #   run: git add -A
      # - name: Commit changes
      #   working-directory: dist/extensions
      #   run: git commit -m "${{github.job}}"
      # - name: Push
      #   working-directory: dist/extensions
      #   run: git push origin dist --force
